version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "tomeeo/feature/ahn-thread-dumps"
    labels:
      - "Prod"
      - "SCA"
