on: push
name: Build

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Run Specs
        run: |
          bundle exec rake
